GET http://localhost:3000/

###
GET http://localhost:3000/63d20ef25df7f067df368a80
###

POST http://localhost:3000/
Content-Type: application/json

{
    "quote": "Oh, yeah? Well, the jerk store called. They're running out of you!",
    "name": "George", 
    "season": 8, 
    "episode": 13
}